version: "2"
services: 
    app:
        build: ./manager
        restart: always
        ports:
            - 46000:46000
        volumes:
            - ./manager/:/manager/
        environment:
            - PORT=46000
            - DOCKER_HOST_IP=192.168.1.198:2375
            - PRIVATE_REGISTRY=192.168.1.198:5000
        tty: true
