version: "2"
services: 
    app:
        build: ./manager
        container_name: production_manager
        restart: always
        volumes:
            - ./manager:/manager/
        ports:
            - 46000:46000
        environment:
            - PORT=46000
            - DOCKER_HOST_IP=192.168.1.72:2375
            - PRIVATE_REGISTRY=192.168.1.72:5000
        tty: true
